# Generated by Django 5.0.2 on 2024-03-06 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_product_alter_product_image_bookeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookeddate',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
    ]
