# Generated by Django 5.0.2 on 2024-03-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bookeddate_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
