# Generated by Django 5.0.2 on 2024-03-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
